### ISSUE TITLE
Running ExaMPM with latest Cabana fails while compiling: `Cabana::Grid::particleMigrate`

### ISSUE THREAD

**Issue by dineshadepu** [ECP-copa/ExaMPM#60]
I am encountering this error while trying to run the package:

```
error: return-statement with a value, in function returning ‘void’ [-fpermissive]
  377 |     return Cabana::Grid::particleMigrate( std::forward<Args>( args )... );
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I believe this is due to the latest update of Cabana`.

**Comment by streeve** [comment]
Thanks for pointing this out - just opened a fix, but we'll also go ahead and merge yours since it's deprecated

**Comment by dineshadepu** [comment]
Thank you! I believe there’s nothing more required from my side at the moment.
